### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by NichenFly** [imfly/ember-cli-fullPagejs#1]
Ember-cli version: 2.5.1
others are normal

```
NichendeMacBook-Pro:front nichen$ ember install ember-cli-fullPagejs
Installed packages for tooling via npm.
Unexpected identifier
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.Blueprint.load (/Users/nichen/src/station/front/node_modules/ember-cli/lib/models/blueprint.js:1364:25)
    at Function.Blueprint.lookup (/Users/nichen/src/station/front/node_modules/ember-cli/lib/models/blueprint.js:1339:24)
    at Class.module.exports.Task.extend.lookupBlueprint (/Users/nichen/src/stati
on/front/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:91:22)
```

**Comment by imfly** [comment]
Yes, it`s not published yet.

Now, you can install it by using:

```
ember install ember-cli-fullPagejs
```

and you can use it in *.hbs files:

```
{{#full-page elementId="fullpage"}}
    your code
{{/full-page}}
```
